version: 0.2
    
phases:   
  install:
    # https://github.com/aws/aws-codebuild-docker-images/issues/497
    commands:
      - /usr/local/bin/dotnet-install.sh --channel LTS
   
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore src/API/API.csproj
      
  build:
    commands:
      - echo Build started on `date`
      # - dotnet build src/API/API.csproj
      - dotnet build src/API/API.csproj -c Release -o /app/build
      - echo Test started on `date`
      - dotnet test src/API/API.csproj
      
  post_build:
    commands:
      - echo Publish started on `date`
      # https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/dotnet-linux-platform-bundle-app.html
      - dotnet publish src/API/API.csproj -r linux-x64 -c Release -o /app/publish
      
artifacts:
  files:
    - /app/publish/*