version: '3.0'

services:
  database:
    container_name: database
    image: postgres:13.2
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - database:/var/lib/postgres-132/data
    environment:
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"

volumes:
  database: